### ISSUE TITLE
Make UsesGithubForDevelopment data provider smarter

### ISSUE THREAD

**Issue by sourabhsparkala** [SAP/fosstars-rating-core#122]
An issue in #121 

We use [getMirrorUrl()](https://github-api.kohsuke.org/apidocs/org/kohsuke/github/GHRepository.html#getMirrorUrl()) to check if the given repository is an original repository or a mirror repository. 

```
if (repository.getMirrorUrl() == null || repository.getMirrorUrl().isEmpty()){
    System.out.print("Repository is a original repository");
}
System.out.print("Repository is a mirror repository");
```
But for mirror repos like [apache/tomee](https://github.com/apache/tomee). The `mirror_url` is `null`. Hence, the above check will fail. This issue can be seen in many mirror repos of [apache](https://github.com/apache). 

For reference: The `mirror_url` flag is `true` for [coreutils/coreutils](https://github.com/coreutils/coreutils)

Hence, find an alternative to confirm the verification if a repository is a mirror or an original repository.

**Comment by artem-smotrakov** [comment]
Here are some ideas for improvements:

- Check if description contains the word "mirror"
- Check if pull requests are enabled
- Check if issues are enabled
- Check if commits refers to real users on GitHub (if a repository is imported from other SCM, the commits often don't point to GitHub user ids)
