### ISSUE TITLE
UsesGitHubForDevelopment data provider seems to provide many false-positives

### ISSUE THREAD

**Issue by artem-smotrakov** [SAP/fosstars-rating-core#194]
The feature 'If a project uses GitHub as the main development platform' is almost always No:

https://github.com/SAP/fosstars-rating-core/blob/master/src/main/jupyter/oss/security/SecurityRatingAnalysis.ipynb

But many of the projects use GitHub for development. This looks like a bug in the data provider.

**Comment by sourabhsparkala** [comment]
For reference:
- https://help.github.com/en/github/searching-for-information-on-github/searching-for-repositories#search-based-on-whether-a-repository-is-a-mirror
- https://help.github.com/en/github/getting-started-with-github/finding-ways-to-contribute-to-open-source-on-github#open-source-projects-with-mirrors-on-github
