### ISSUE TITLE
JSON Injection

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [SAP/fosstars-rating-core#20]
https://github.com/SAP/fosstars-rating-core/blob/fab81c0090b92a6df607867475a5d3138a1302a9/src/main/java/com/sap/sgs/phosphor/fosstars/data/lgtm/LgtmDataProvider.java#L85

The method writes unvalidated input into JSON. This call could allow an attacker to inject arbitrary elements or attributes into the JSON entity.

**Comment by artem-smotrakov** [comment]
The JSON comes from `https://lgtm.com/api` which is considered trusted. The class uses HTTPS to prevent tampering data in the middle. The JDK on user's machine should be configured with a correct set of trusted certificates to prevent a successful man-in-the-middle attack.

Please re-open this issue and provide more details if you think there is another problem.
