### ISSUE TITLE
Update of required after cleanup in GitHubDataFetcher

### ISSUE THREAD

**Issue by mibo** [SAP/fosstars-rating-core#210]
During some test with `GitHubDataFetcher` and the `cleanup()` method it looks like that use of more than one instance of `GitHubDataFetcher` leads to invalid/outdated data in `localRepositoriesInfo`

As if instance A of `GitHubDataFetcher` runs the `cleanup()` and afterwards a new instance B is created it loads the outdated information via `loadLocalRepositoriesInfo()` in the c'tor.

Perhaps after the clean up is finished [see here](https://github.com/SAP/fosstars-rating-core/blob/0d28e118ddbf158a10efe38d4828a629a3371b0c/src/main/java/com/sap/sgs/phosphor/fosstars/data/github/GitHubDataFetcher.java#L396) the `storeLocalRepositoriesInfo()` should be called (and a `synchronized` be added to the `storeLocalRepositoriesInfo()`).

Maybe this is not a harmful bug or not a bug at all, but at least I wanted to ask 🙂

**Comment by artem-smotrakov** [comment]
This seems to be related to #217 and #221
