### ISSUE TITLE
Assessing number of vulnerabilities together with security testing

### ISSUE THREAD

**Issue by artem-smotrakov** [SAP/fosstars-rating-core#224]
A number of vulnerabilities and their severities can't tell much about security in an open-source project. However, it may make sense to assess info about vulnerabilities together with info about security testing implemented in the project. It may be implemented in a score that has the following logic:

|   |  Bad testing | Good testing |
|---|---|---|
| Few vulnerabilities | Low score | Max score  |
| Many vulnerabilities | Min score  | High score  |

The logic is quite simple. It may be improved, for example, by taking into account severity of vulnerabilities.

**Comment by Sachpat** [comment]
The logic itself looks good. Is there a way to include open(non-resolved) vulnerabilities in this? Also a question to know better, how do we know about Good testing?

**Comment by artem-smotrakov** [comment]
> Is there a way to include open(non-resolved) vulnerabilities in this? 

I believe we can find such a way. The problem is that it's hard to collect resolution status for issues. Currently, we only have a static list of unpatched vulnerabilities that is maintained manually.

> Also a question to know better, how do we know about Good testing?

The `ProjectSecurityTestingScore` currently assesses how a project implements security testing. We can use it in the new score. We'll need to set a threshold what defines Good testing.

**Comment by Sachpat** [comment]
Thanks for the clarification. 
>We'll need to set a threshold that defines Good testing.
Yeah makes sense. 
> The problem is that it's hard to collect resolution status for issues.
Yeah if we can somehow get a way to collect such, would make this score perfect.

Also, how about having time factor in this? something like many vulnerabilities in recent times or in the past 1 year or something?

**Comment by artem-smotrakov** [comment]
> Also, how about having time factor in this? something like many vulnerabilities in recent times or in the past 1 year or something?

Sure. If you have an idea how exactly it may be implemented, please let me know.

**Comment by Sachpat** [comment]
|   |  Bad testing | Good testing |
|---|---|---|
| Few vulnerabilities | Low score | Max score  |
| Many vulnerabilities | Mid score (if not so many in last 1 year)/Min score  (if there are many in last x years) | High score (if there are many in last x years) /   Max score (if there are not so many in last x years)

Something like this? just an Idea, if it doesn't make sense, fine to drop it )

**Comment by artem-smotrakov** [comment]
Maybe the score can only consider issues in last X years. I'll have a closer look. But I am not sure if a high score should be returned for a project that has bad security teting.

**Comment by Sachpat** [comment]
>But I am not sure if a high score should be returned for a project that has bad security teting.

I agree that shouldn't be there.

**Comment by artem-smotrakov** [comment]
It might be possible to consider `HAS_BUG_BOUNTY` feature in the new score as well.
