### ISSUE TITLE
Add a label for unclear ratings

### ISSUE THREAD

**Issue by mibo** [SAP/fosstars-rating-core#253]
To better indicate that the calculated rating has a low confidence the label should be `UNCLEAR` instead of the calculated (and mostly `BAD` label).

It should be possible to set a threshold to define all calculated ratings with a confidence below the threshold will have the new `UNCLEAR` label.

Like it was done for the [security statistics overview](https://github.com/SAP/fosstars-rating-core/tree/be5711a9757341663a1c63df6ba5f6535b1c351c/docs/oss/security).

**Comment by artem-smotrakov** [comment]
Let's consider this option.
