### ISSUE TITLE
Make the method find() in AbstractScore efficient

### ISSUE THREAD

**Issue by sourabhsparkala** [SAP/fosstars-rating-core#278]
The `find()` method allows us to find the required `value` from the list of `values`. But somehow the returned value class does not coincide with the expected return class.

That is:
The class `OwaspDependencyCheckCvssThreshold` has the value definition of type `OwaspDependencyCheckCvssThresholdValue`. But the `find()` does not resolve this return type.

What should happen?
`find()` should return the appropriate return types.

**Comment by artem-smotrakov** [comment]
When we discussed it, I forgot that `find()` may also return `UnknownValue` and `NotApplicableValue`. Scores should expect that. That's why the method has to return `Value`.
