### ISSUE TITLE
It seems to be possible that there are more contributors than commits

### ISSUE THREAD

**Issue by mibo** [SAP/fosstars-rating-core#34]
It seems to be possible that there are more contributors than commits (in the last three months).
In the sample project https://github.com/jdesboeufs/connect-mongo we encountered above situation

- "name":"Number of commits last three months","n":2
- "name":"Number of contributors last three months","n":3

Which leads to a `java.lang.IllegalArgumentException: More commits than contributors! How is that possible?`

Must the check [in the ProjectActivityScore](https://github.com/SAP/fosstars-rating-core/blob/d7ec6024537cccb13c22f221968231a527efd898/src/main/java/com/sap/sgs/phosphor/fosstars/model/score/oss/ProjectActivityScore.java#L139) changed/removed?

**Comment by artem-smotrakov** [comment]
Yeah, looks like this check is based on the wrong assumption:

```java
if (m > n) {
      throw new IllegalArgumentException("More commits than contributors! How is that possible?");
    }
```

Let's remove the check.
