### ISSUE TITLE
3 tests are failing during `mvn clean install`

### ISSUE THREAD

**Issue by SebastianWolf-SAP** [SAP/fosstars-rating-core#429]
If I execute a `mvn clean install` on a freshly cloned repository, the packaging fails constantly with 3 unit test errors:

```
[ERROR] Errors:
[ERROR]   FuzzedInOssFuzzTest.testFetchValueFor:48 » JGitInternal Unable to find a publi... 
[ERROR]   LocalRepositoryTest.testCommitHistory:87 » JGitInternal Unable to find a publi...
[ERROR]   LocalRepositoryTest.testReadFile:49 » JGitInternal Unable to find a public-key...    
```

Also the quickfix from https://github.com/SAP/fosstars-rating-core/tree/fix-git-commit doesn't fix it - same symptom.

My configuration:
- Windows 10, version 1909
- Using WSL1 running OpenSUSE 15.2
- Java: openjdk 11.0.10 2021-01-19  
- Maven: Apache Maven 3.6.3 (SUSE 3.6.3-lp152.20.105)

**Comment by artem-smotrakov** [comment]
Looks like a test bug.

I have never seen this before. The failed tests try to commit something to a temp repository using JGit. Seems like they can't find user credentials. I am not sure where JGit get credentials from. I could not reproduce the issue in several environments.

**Comment by artem-smotrakov** [comment]
Okay, looks like the tests fail when something goes wrong with GPG. JGit seems to load Git settings, and use them for `CommitCommand`. If GPG signing is configured, then the tests fail if JGit fails to load GPG keys.

I could reproduce the issue after configuring GPG signing with a wrong GPG key

```
$ git config --global commit.gpgsign true
$ git config --global user.signingkey wrong
```

**Comment by artem-smotrakov** [comment]
The tests need to be fixed anyway. They should not depend on local Git configs.
