### ISSUE TITLE
Read and parse CPE information from NVD to improve mapping of projects to CPE

### ISSUE THREAD

**Issue by mibo** [SAP/fosstars-rating-core#468]
Read and parse [CPE](https://nvd.nist.gov/products/cpe) information from NVD to improve mapping of projects to CPE.
In addition this would improve the mapping from projects to CVE (via CPE).

The CPE entries have (compared to CVEs) additional reference information:

```
  <cpe-item name="cpe:/a:apache:olingo:-">
    <title xml:lang="en-US">Apache Software Foundation Olingo</title>
    <references>
      <reference href="https://github.com/apache/olingo-odata4">Version</reference>
    </references>
    <cpe-23:cpe23-item name="cpe:2.3:a:apache:olingo:-:*:*:*:*:*:*:*"/>
  </cpe-item>

```

**Comment by mibo** [comment]
Just learned that OWASP Dependency Check (or other tools) maybe have already a solution for this which can be used.
Before we start to work on an own implementation we will check for alternative implementations.

**Comment by artem-smotrakov** [comment]
> Just learned that OWASP Dependency Check (or other tools) maybe have already a solution for this which can be used.
> Before we start to work on an own implementation we will check for alternative implementations.

Yes, agree, I would also look for existing implementations for project-CPE mapping before implementing our own one. [OWASP Dependency Check](https://github.com/jeremylong/DependencyCheck) or [Steady](https://github.com/eclipse/steady) should definitely have such an implementation and it is open source.

**Comment by sourabhsparkala** [comment]
This can be closed now. As we had a chance to go through this #534

@artem-smotrakov @mibo. Please let me know what you think.

**Comment by artem-smotrakov** [comment]
> This can be closed now. As we had a chance to go through this #534
> 
> @artem-smotrakov @mibo. Please let me know what you think.

Yeah, I think we can close it.

**Comment by sourabhsparkala** [comment]
Closing this now.
