### ISSUE TITLE
Remove code duplication in OssArtifactSecurityRatingMarkdownFormatter

### ISSUE THREAD

**Issue by mibo** [SAP/fosstars-rating-core#486]
Remove code duplication in `OssArtifactSecurityRatingMarkdownFormatter`.

- One option may be to add new superclass used by `OssSecurityRatingMarkdownFormatter` and `OssArtifactSecurityRatingMarkdownFormatter` as both have > 90% same code.
- Another option may be pass the resource (e.g. `OssArtifactSecurityRatingMarkdownRatingValueTemplate.md`) when the formatter are created (in `com.sap.oss.phosphor.fosstars.tool.github.Application#createFormatter`).

_Originally posted by @artem-smotrakov in https://github.com/SAP/fosstars-rating-core/pull/423#discussion_r600517245_

**Comment by artem-smotrakov** [comment]
See also #483

**Comment by artem-smotrakov** [comment]
This will be addressed in #483
