### ISSUE TITLE
Introduce VulnerableArtifact for Vulnerability

### ISSUE THREAD

**Issue by mibo** [SAP/fosstars-rating-core#487]
Introduce `VulnerableArtifact` for `Vulnerability` which holds the name (CPE?) and the version range for an artifact which is affected by they `Vulnerability`.
The `Vulnerability` would then hold a list of `VulnerableArtifact` (or maybe `AffectedArtifact`?).

**Comment by artem-smotrakov** [comment]
I am not sure yet but it may be better to add have a list of vulnerabilities in `ArtifactVersion`. There are vulnerabilities that affect multiple artifacts (or even projects). Furthermore, `ArtifactVersion` should implement `Subject`.

**Comment by mibo** [comment]
Based on the latest changes (e.g. in #534 and others) this issue and the related PR #508 are not relevant anymore.  
Hence, yes I close this issue.
