### ISSUE TITLE
Enhance how default values for known values can be provided in Application

### ISSUE THREAD

**Issue by mibo** [SAP/fosstars-rating-core#488]
Enhance how known values can be provided in Application.

Idea is to provide the default values via a dummy data provider that just returns a pre-defined values.
See [comment](https://github.com/SAP/fosstars-rating-core/pull/423#discussion_r601615063).

**Comment by artem-smotrakov** [comment]
Known values have been removed by #580

**Comment by artem-smotrakov** [comment]
We'll implement https://github.com/SAP/fosstars-rating-core/pull/423#discussion_r601615063 later if necessary.
