### ISSUE TITLE
ArtifactVersionsValue.isUnknown() should return false

### ISSUE THREAD

**Issue by artem-smotrakov** [SAP/fosstars-rating-core#509]
https://github.com/SAP/fosstars-rating-core/blob/e21dca466de6bbac96757d983d2010c2dad0b64e/src/main/java/com/sap/oss/phosphor/fosstars/model/value/ArtifactVersionsValue.java#L40

Currently, an `ArtifactVersionsValue` is known if its `ArtifactVersions` is not empty. However, an empty collection is a valid known value that just means that there is no artifact versions.

**Comment by mibo** [comment]
I can take this issue and fix it in #505

**Comment by artem-smotrakov** [comment]
Sure @mibo , please go ahead and fix it -- thanks!

**Comment by artem-smotrakov** [comment]
@mibo FIY while fixing #512, I had to fix this issue as well https://github.com/SAP/fosstars-rating-core/pull/513
