### ISSUE TITLE
Rename SecurityLabel.OKAY to SecurityLabel.MODERATE

### ISSUE THREAD

**Issue by mibo** [SAP/fosstars-rating-core#56]
The difference between GOOD and OKAY looks not that clear (in `com.sap.sgs.phosphor.fosstars.model.rating.oss.OssSecurityRating` the `SecurityLabel` enum).

I suggest to rename the `OKAY` to `MODERATE`. 
IMHO this fits better between `GOOD` and `BAD`.
Result would be:
```
public enum SecurityLabel implements Label {
  BAD, MODERATE, GOOD
}
```

See related PR #57 which I have created.

**Comment by artem-smotrakov** [comment]
I agree. The score range for `OKAY` doesn't really mean okay. The MODERATE label fits better to the range.
