### ISSUE TITLE
Project popularity score: 3.38 for jackson-databind

### ISSUE THREAD

**Issue by Sachpat** [SAP/fosstars-rating-core#630]
Though Jackson-databind is quite popular and widely used, we get the the Project popularity score as 3.38 for the same with the below details:

```
Project popularity
Score: 3.38, confidence is 10.0 (max), weight is 0.5 (medium)

The score is based on number of stars and watchers. Here is how a number of stars contributes to the score: 0 -> 0.00 (min), 2500 -> 2.50, 5000 -> 5.00, 10000 -> 10.00 (max) Here is how a number of watchers contributes to the score: 0 -> 0.00 (min), 450 -> 1.50, 750 -> 2.50, 3000 -> 10.00 (max)

This sub-score is based on 2 features:

Number of stars for a GitHub repository: 2858
Number of watchers for a GitHub repository: 158
```

I would expect some 8 to 9 as the Project popularity score for it as its widely used and known in Open source community.

**Comment by artem-smotrakov** [comment]
Good point. We may need to update the threshold in the scoring function and/or find other data sources that would help to assess popularity of an open source project.

**Comment by artem-smotrakov** [comment]
I've tried to get the "Used by" number from the GraphQL API but unfortunately it didn't work out

https://til.simonwillison.net/github/dependencies-graphql-api
