### ISSUE TITLE
Issue creation should check if issues are enabled

### ISSUE THREAD

**Issue by SebastianWolf-SAP** [SAP/fosstars-rating-core#660]
The new issue creation functionality of course doesn't work if issues are disabled for the respective repository. Instead of trying to create issues for findings, it should check the settings beforehand to avoid error messages in the log.

Errors:
```
[!] Oops! Could not create issues for https://github.com/org/repo
org.kohsuke.github.GHFileNotFoundException: https://api.github.com/repos/org/repo/issues {"message":"Issues are disabled for this repo","documentation_url":"https://docs.github.com/v3/issues/"}
```

**Comment by artem-smotrakov** [comment]
Yeah, it should check if issues are enabled.
