### ISSUE TITLE
Unifying the data gathering process for data providers

### ISSUE THREAD

**Issue by sourabhsparkala** [SAP/fosstars-rating-core#69]
Data Providers like:
- `FirstCommit` 
- `ProjectStarted` 
- `NumberOfCommits`
- `UsesSignedCommits`

Use commit history. It takes a toll on the performance when `fosstars-rating-core` try to hit the `GitHub API` again and again for each data provider to get the same data. 

To avoid this redundant work, merge the data gathering method for all the above-mentioned data providers.

**Comment by artem-smotrakov** [comment]
https://github.com/github-api/github-api/issues/737 has been fixed. Let's wait for this to be included in the next release.

**Comment by artem-smotrakov** [comment]
v1.109 contains the APIs for working with verified signed commits

https://github.com/github-api/github-api/releases/tag/github-api-1.109

We can now start working on this issue.
