### ISSUE TITLE
Non-Determinism In Unit Test

### ISSUE THREAD

**Issue by jchen8460** [SAP/fosstars-rating-core#817]
There is non-deterministic behavior in the test `com.sap.oss.phosphor.fosstars.data.artifact.VulnerabilitiesFromOwaspDependencyCheckTest.testVulnerabilitiesAvailable`. It comes from assuming a specific order when using the `HashSet` iterator. As stated by the Javadoc, "It makes no guarantees as to the iteration order of the set; in particular, it does not guarantee that the order will remain constant over time." This issue was found by the tool [NonDex](https://github.com/TestingResearchIllinois/NonDex).

I already have a solution for this test. All of the vulnerability id's can be added into a `HashSet`. Then, the specific id can be searched for in the `HashSet`. This ensures that the test will always pass even if the iteration order changes. Please let me know if you want me to open the PR.

**Comment by sourabhsparkala** [comment]
> There is non-deterministic behavior in the test `com.sap.oss.phosphor.fosstars.data.artifact.VulnerabilitiesFromOwaspDependencyCheckTest.testVulnerabilitiesAvailable`. It comes from assuming a specific order when using the `HashSet` iterator. As stated by the Javadoc, "It makes no guarantees as to the iteration order of the set; in particular, it does not guarantee that the order will remain constant over time." This issue was found by the tool [NonDex](https://github.com/TestingResearchIllinois/NonDex).
> 
> I already have a solution for this test. All of the vulnerability id's can be added into a `HashSet`. Then, the specific id can be searched for in the `HashSet`. This ensures that the test will always pass even if the iteration order changes. Please let me know if you want me to open the PR.

@jchen8460 overall it sounds like a good idea. Now that I look at it, its just lazy coding on our end. Please go ahead and create a PR on your free time. Thanks for the contribution.

**Comment by sourabhsparkala** [comment]
This issue is resolved with #823
