### ISSUE TITLE
Missing info on how to fix the issue

### ISSUE THREAD

**Issue by fwilhe** [SAP/fosstars-rating-core#905]
Hi,

we've got [this issue](https://github.com/SAP-samples/cloud-sdk-js/issues/560) in our repo and I don't understand what's wrong and how we can fix it.

It's mentioning 'rl-reuse_tool-4' which seems to mean 'If a project is compliant with REUSE rules', but if I run the cli with this commend `docker run -v $(pwd):/work fosstars --rating oss-rules-of-play --token mytoken --url https://github.com/SAP-samples/cloud-sdk-js --verbose`

it contradicts this statement

```
[+] Here is how the rating was calculated:
[+]   Score:........Open source rules or play score
[+]   Description:..The score shows whether an open source project
[+]                 violates rules or not.
[+]   Value:........0.0  out of 10.0
[+]   Confidence:...Low (7.83 out of 10.0)
[+]   Based on:...23 features
[+]       Are vulnerability alerts enabled?.........................No
[+]       Does README mention REUSE?................................Yes
[+]       Does it have LICENSES directory with licenses?............Yes
[+]       Does it have a README file?...............................Yes
[+]       Does it have a code of conduct guideline?.................Yes
[+]       Does it have a contributing guideline?....................Yes
[+]       Does it have a license file?..............................Yes
[+]       Does it have a security policy?...........................Yes
[+]       Does it have a team with push privileges on GitHub?.......unknown
[+]       Does it have an admin team on GitHub?.....................unknown
[+]       Does it have enough admins on GitHub?.....................unknown
[+]       Does it have enough teams on GitHub?......................unknown
[+]       Does it have unresolved vulnerability alerts?.............Yes
[+]       Does it run CodeQL scans?.................................Yes
[+]       Does it use CodeQL checks for pull requests?..............Yes
[+]       Does it use an allowed license?...........................No
[+]       Does teams have enough members on GitHub?.................unknown
[+]       Does the code of conduct guideline have required text?....Yes
[+]       Does the contributing guideline have required text?.......Yes
[+]       Does the license have disallowed content?.................No
[+]       Is README incomplete?.....................................No
[+]       Is it compliant with REUSE rules?.........................Yes
[+]       Is it registered in REUSE?................................Yes
[+]   Explanation:..Found 2 violated rules
[+]
[+] Rating:     0.0  out of 10.0 -> FAILED
[+] Confidence: Low (7.83 out of 10.0)
```

see -> 'Is it compliant with REUSE rules?.........................Yes'

I assume it might be an issue that we have some files which can't be licensed under an oss license, but we've configured REUSE in accordance with what OSPO told us, so I'm not sure what's wrong and how we can fix it. See [here](https://github.com/SAP-samples/cloud-sdk-js/blob/main/.reuse/dep5#L31) for that REUSE config.

Not sure what the 'Found 2 violated rules' exactly are. What does 'Does it use an allowed license?' mean? The github api reports our project as Apache 2 licensed (which is true except for the edmx files)

Can I see the exact condition that leads to this issue being created somewhere?

Thanks,
Florian

**Comment by fwilhe** [comment]
@sourabhsparkala can you help here?

**Comment by SebastianWolf-SAP** [comment]
Seems that the issue has already been fixed or it simply was a temporary false positive. Your 'official' result which is also used to evaluate the rating is available here (and referenced from your README): https://api.reuse.software/info/github.com/SAP-samples/cloud-sdk-js

Therefore, you can simply close this issue without any further action needed (I can do that for you).

More details about how to make your project REUSE-compliant in case there is a real issue can be found at https://reuse.software/tutorial/ and in our internal wiki.

**Comment by fwilhe** [comment]
Thanks @SebastianWolf-SAP 

I'd still appreciate if the issue would include more information that makes it easier to triage if that is possible.
