### ISSUE TITLE
attachment repo gets issue: rl-assigned_teams-1

### ISSUE THREAD

**Issue by adamandre79** [SAP/fosstars-rating-core#994]
Hello colleagues,

on my repo: https://github.com/cap-java/cds-feature-attachments
I got an [issue](https://github.com/cap-java/cds-feature-attachments/issues/104) opened with:

Rule ID: rl-assigned_teams-1
Explanation: Does it have enough teams on GitHub? No

In the attached [explanation](https://sap.github.io/fosstars-rating-core/oss_rules_of_play_rating.html) I only found:
"Whether the project has at least two teams assigned or not."

Could you please give some insights why I need to assign two teams? So why not only one team is enough?
What is the purpose of the second team?

Regards
André

**Comment by ajinkyapatil8190** [comment]
The repository is now compliant - 
![image](https://github.com/SAP/fosstars-rating-core/assets/13133800/3a58328b-14f0-4f50-9778-117e9bb58219)
I am closing this issue.
